### ISSUE TITLE
Infografía conceptos y fases de gestión de proyectos de software

### ISSUE THREAD

**Issue by garaudy12** [SistemasTecTlaxiaco/infografia-garaudy12-1#2]
[Infografía Taoli Solano.pdf](https://github.com/SistemasTecTlaxiaco/infografia-garaudy12-1/files/7149003/Infografia.Taoli.Solano.pdf)

**Comment by Jaimer117** [comment]
calificación 20%

**Comment by josealfredo79** [comment]
Faltan agregar metodologías, herramientas y buenas practicas.

**Comment by garaudy12** [comment]
[Infografía.pdf](https://github.com/SistemasTecTlaxiaco/infografia-garaudy12-1/files/7187631/Infografia.pdf)
